### PR TITLE
Name now gets dynamically loaded into page

### PR DESCRIPTION
**Pull request by ashivkum**
Moving to make stats.ctp completely static HTML

### CODE REVIEW

**Comment by ghost** [comment]
I think I made a big mess out of this when I tried to merge the last pull request into this branch. The changes that you're trying to make here all look good to me but I'm going to hold off on merging this pull request because I think it'll overwrite some of the changes from the last one? My working knowledge of git is almost exactly this: https://xkcd.com/1597/

**Comment by ashivkum** [comment]
According to Git, this branch has no conflicts with the base branch.  I can test this on my local git and see that merging this won't have any merge conflicts.

EDIT: Well, apparently it does!  I'll fix the merge conflicts and just merge it in manually.

**Comment by ashivkum** [comment]
Closed because merged.

**Comment by ghost** [comment]
ha cool thanks!

On Mon, Apr 18, 2016 at 8:01 PM, ashivkum notifications@github.com wrote:

> Closed because merged.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/cmj7gh/ClientTracker/pull/8#issuecomment-211639187

## 

Chris Jones
UVA Class of 2013
School of Engineering and Applied Sciences

**Pull request closed without merging**
